"""Add node_tasks table

Revision ID: d827b75c8604
Revises: 13performance_indexes
Create Date: 2026-01-28 10:36:51.936491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd827b75c8604'
down_revision: Union[str, None] = '13performance_indexes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('why', sa.Text(), nullable=True),
    sa.Column('tip', sa.Text(), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('activities', 'extra_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('activities', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('activities', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('ix_activities_created_at', table_name='activities')
    op.drop_index('ix_activities_target', table_name='activities')
    op.drop_index('ix_activities_user_id', table_name='activities')
    op.alter_column('badges', 'category',
               existing_type=postgresql.ENUM('achievement', 'social', 'streak', 'milestone', 'special', name='badgecategory'),
               nullable=False)
    op.alter_column('badges', 'rarity',
               existing_type=postgresql.ENUM('common', 'rare', 'epic', 'legendary', name='badgerarity'),
               nullable=False)
    op.alter_column('comments', 'is_edited',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('comments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('ix_comments_parent_id', table_name='comments')
    op.drop_index('ix_comments_target', table_name='comments')
    op.drop_index('ix_comments_user', table_name='comments')
    op.drop_index('ix_comments_user_id', table_name='comments')
    op.drop_index('ix_follows_target', table_name='follows')
    op.drop_index('ix_generation_queue_created_at', table_name='generation_queue')
    op.drop_index('ix_generation_queue_status', table_name='generation_queue')
    op.alter_column('goal_shares', 'permission',
               existing_type=postgresql.ENUM('view', 'edit', name='sharepermission'),
               nullable=False,
               existing_server_default=sa.text("'view'::sharepermission"))
    op.alter_column('goal_shares', 'status',
               existing_type=postgresql.ENUM('pending', 'accepted', 'declined', name='sharestatus'),
               nullable=False,
               existing_server_default=sa.text("'pending'::sharestatus"))
    op.alter_column('goal_shares', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('ix_goal_shares_goal_id', table_name='goal_shares')
    op.drop_index('ix_goal_shares_shared_with_user_id', table_name='goal_shares')
    op.drop_index('ix_goals_discovery', table_name='goals')
    op.drop_index('ix_goals_user_visibility', table_name='goals')
    op.drop_index('ix_interactions_target', table_name='interactions')
    op.alter_column('node_dependencies', 'dependency_type',
               existing_type=postgresql.ENUM('finish_to_start', 'start_to_start', 'finish_to_finish', name='dependencytype'),
               nullable=False,
               existing_server_default=sa.text("'finish_to_start'::dependencytype"))
    op.alter_column('node_dependencies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('ix_node_dependencies_depends_on_id', table_name='node_dependencies')
    op.drop_index('ix_node_dependencies_node_id', table_name='node_dependencies')
    op.drop_constraint('uq_node_dependency', 'node_dependencies', type_='unique')
    op.alter_column('nodes', 'can_parallel',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('ix_nodes_difficulty', table_name='nodes')
    op.drop_index('ix_nodes_goal_status', table_name='nodes')
    op.alter_column('prophecies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('ix_prophecies_goal_id', table_name='prophecies')
    op.drop_index('ix_prophecies_user_id', table_name='prophecies')
    op.alter_column('resource_drops', 'resources',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('resource_drops', 'is_opened',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('resource_drops', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('ix_resource_drops_node_id', table_name='resource_drops')
    op.drop_index('ix_resource_drops_user_id', table_name='resource_drops')
    op.alter_column('sacred_boosts', 'xp_awarded',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('50'))
    op.alter_column('sacred_boosts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('ix_sacred_boosts_boost_date', table_name='sacred_boosts')
    op.drop_index('ix_sacred_boosts_giver_goal_date', table_name='sacred_boosts')
    op.drop_index('ix_sacred_boosts_giver_id', table_name='sacred_boosts')
    op.drop_index('ix_sacred_boosts_goal_id', table_name='sacred_boosts')
    op.drop_index('ix_sacred_boosts_year_month', table_name='sacred_boosts')
    op.drop_index('ix_swaps_proposer_id', table_name='swaps')
    op.drop_index('ix_swaps_receiver_id', table_name='swaps')
    op.drop_index('ix_swaps_status', table_name='swaps')
    op.drop_index('ix_time_capsules_is_unlocked', table_name='time_capsules')
    op.drop_index('ix_time_capsules_node_id', table_name='time_capsules')
    op.drop_index('ix_time_capsules_sender_id', table_name='time_capsules')
    op.alter_column('user_stats', 'goals_created',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_stats', 'goals_completed',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_stats', 'nodes_completed',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_stats', 'comments_given',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_stats', 'reactions_given',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_stats', 'comments_received',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_stats', 'reactions_received',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_stats', 'followers_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_stats', 'following_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_stats', 'achiever_score',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_stats', 'supporter_score',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_stats', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_stats', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user_stats', 'supporter_score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user_stats', 'achiever_score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user_stats', 'following_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user_stats', 'followers_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user_stats', 'reactions_received',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user_stats', 'comments_received',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user_stats', 'reactions_given',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user_stats', 'comments_given',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user_stats', 'nodes_completed',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user_stats', 'goals_completed',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user_stats', 'goals_created',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index('ix_time_capsules_sender_id', 'time_capsules', ['sender_id'], unique=False)
    op.create_index('ix_time_capsules_node_id', 'time_capsules', ['node_id'], unique=False)
    op.create_index('ix_time_capsules_is_unlocked', 'time_capsules', ['is_unlocked'], unique=False)
    op.create_index('ix_swaps_status', 'swaps', ['status'], unique=False)
    op.create_index('ix_swaps_receiver_id', 'swaps', ['receiver_id'], unique=False)
    op.create_index('ix_swaps_proposer_id', 'swaps', ['proposer_id'], unique=False)
    op.create_index('ix_sacred_boosts_year_month', 'sacred_boosts', ['year_month'], unique=False)
    op.create_index('ix_sacred_boosts_goal_id', 'sacred_boosts', ['goal_id'], unique=False)
    op.create_index('ix_sacred_boosts_giver_id', 'sacred_boosts', ['giver_id'], unique=False)
    op.create_index('ix_sacred_boosts_giver_goal_date', 'sacred_boosts', ['giver_id', 'goal_id', 'boost_date'], unique=False)
    op.create_index('ix_sacred_boosts_boost_date', 'sacred_boosts', ['boost_date'], unique=False)
    op.alter_column('sacred_boosts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('sacred_boosts', 'xp_awarded',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('50'))
    op.create_index('ix_resource_drops_user_id', 'resource_drops', ['user_id'], unique=False)
    op.create_index('ix_resource_drops_node_id', 'resource_drops', ['node_id'], unique=False)
    op.alter_column('resource_drops', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('resource_drops', 'is_opened',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('resource_drops', 'resources',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_index('ix_prophecies_user_id', 'prophecies', ['user_id'], unique=False)
    op.create_index('ix_prophecies_goal_id', 'prophecies', ['goal_id'], unique=False)
    op.alter_column('prophecies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index('ix_nodes_goal_status', 'nodes', ['goal_id', 'status'], unique=False)
    op.create_index('ix_nodes_difficulty', 'nodes', ['difficulty'], unique=False)
    op.alter_column('nodes', 'can_parallel',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_unique_constraint('uq_node_dependency', 'node_dependencies', ['node_id', 'depends_on_id'])
    op.create_index('ix_node_dependencies_node_id', 'node_dependencies', ['node_id'], unique=False)
    op.create_index('ix_node_dependencies_depends_on_id', 'node_dependencies', ['depends_on_id'], unique=False)
    op.alter_column('node_dependencies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('node_dependencies', 'dependency_type',
               existing_type=postgresql.ENUM('finish_to_start', 'start_to_start', 'finish_to_finish', name='dependencytype'),
               nullable=True,
               existing_server_default=sa.text("'finish_to_start'::dependencytype"))
    op.create_index('ix_interactions_target', 'interactions', ['target_type', 'target_id', 'interaction_type'], unique=False)
    op.create_index('ix_goals_user_visibility', 'goals', ['user_id', 'visibility'], unique=False)
    op.create_index('ix_goals_discovery', 'goals', ['visibility', 'updated_at'], unique=False)
    op.create_index('ix_goal_shares_shared_with_user_id', 'goal_shares', ['shared_with_user_id'], unique=False)
    op.create_index('ix_goal_shares_goal_id', 'goal_shares', ['goal_id'], unique=False)
    op.alter_column('goal_shares', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('goal_shares', 'status',
               existing_type=postgresql.ENUM('pending', 'accepted', 'declined', name='sharestatus'),
               nullable=True,
               existing_server_default=sa.text("'pending'::sharestatus"))
    op.alter_column('goal_shares', 'permission',
               existing_type=postgresql.ENUM('view', 'edit', name='sharepermission'),
               nullable=True,
               existing_server_default=sa.text("'view'::sharepermission"))
    op.create_index('ix_generation_queue_status', 'generation_queue', ['status'], unique=False)
    op.create_index('ix_generation_queue_created_at', 'generation_queue', ['created_at'], unique=False)
    op.create_index('ix_follows_target', 'follows', ['target_id', 'follow_type'], unique=False)
    op.create_index('ix_comments_user_id', 'comments', ['user_id'], unique=False)
    op.create_index('ix_comments_user', 'comments', ['user_id'], unique=False)
    op.create_index('ix_comments_target', 'comments', ['target_type', 'target_id'], unique=False)
    op.create_index('ix_comments_parent_id', 'comments', ['parent_id'], unique=False)
    op.alter_column('comments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('comments', 'is_edited',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('badges', 'rarity',
               existing_type=postgresql.ENUM('common', 'rare', 'epic', 'legendary', name='badgerarity'),
               nullable=True)
    op.alter_column('badges', 'category',
               existing_type=postgresql.ENUM('achievement', 'social', 'streak', 'milestone', 'special', name='badgecategory'),
               nullable=True)
    op.create_index('ix_activities_user_id', 'activities', ['user_id'], unique=False)
    op.create_index('ix_activities_target', 'activities', ['target_type', 'target_id'], unique=False)
    op.create_index('ix_activities_created_at', 'activities', ['created_at'], unique=False)
    op.alter_column('activities', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('activities', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('activities', 'extra_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_table('node_tasks')
    # ### end Alembic commands ###
