from datetime import datetime
from typing import Optional, List
from uuid import UUID
from pydantic import BaseModel, Field
from app.models.generation_queue import QueueStatus


class QueueSubmitRequest(BaseModel):
    """Request to submit a goal for AI generation"""
    goal_text: str = Field(..., min_length=5, max_length=500, description="The goal description, e.g., 'run a marathon in 3 months'")


class QueueSubmitResponse(BaseModel):
    """Response after submitting to queue"""
    queue_id: UUID
    status: QueueStatus
    message: str
    position: int = Field(..., description="Position in queue (1 = next to process)")


class QueueStatusResponse(BaseModel):
    """Response for checking queue status"""
    queue_id: UUID
    status: QueueStatus
    goal_text: str
    goal_id: Optional[UUID] = None
    error_message: Optional[str] = None
    created_at: datetime
    processing_started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    estimated_wait_seconds: Optional[int] = None


class GeneratedNode(BaseModel):
    """A node generated by the AI"""
    order: int
    title: str
    description: str
    duration_estimate: Optional[str] = None
    success_criteria: Optional[str] = None
    tips: Optional[str] = None


class GeneratedPlan(BaseModel):
    """The complete AI-generated plan"""
    title: str
    description: str
    category: str
    world_theme: str
    target_date: Optional[str] = None
    nodes: List[GeneratedNode]


class QueueItemForProcessing(BaseModel):
    """Queue item as shown to the processor (CLI)"""
    queue_id: UUID
    user_email: str
    goal_text: str
    created_at: datetime
    waiting_seconds: int


class ProcessQueueRequest(BaseModel):
    """Request to save processed plan"""
    queue_id: UUID
    plan: GeneratedPlan
